### ISSUE TITLE
Colors

### ISSUE THREAD

**Issue by galensoft** [danielkvist/hugo-terrassa-theme#1]
Hello, I like your theme! 
This is not really an issue but more of a newbie question...

How do I change the background color of the page?

Thank you for your time and hard work!

**Comment by galensoft** [comment]
I just found it... Thanks!

**Comment by dnlzrgz** [comment]
Hi @eriknielsen! 
I'm not sure what your problem was, but I'm glad it's been solved.
If there is any part of the documentation that you think needs to be improved or if you have any further questions please let me know!
