### ISSUE TITLE
Use of .Hugo is deprecated

### ISSUE THREAD

**Issue by coreyt** [danielkvist/hugo-terrassa-theme#13]
When building the site, I am receiving a warning:
`Building sites . WARN 2019/06/01 12:28:30 Page's .Hugo is deprecated and will be removed in a future release. Use the global hugo function.`

**Comment by coreyt** [comment]
Contributed fix in #14

**Comment by dnlzrgz** [comment]
Again, thank you very much for your contribution!

Since the problem is fixed, I'm going to close this issue.
