### ISSUE TITLE
How do I change the hero image on the homepage?

### ISSUE THREAD

**Issue by JohnBlood** [danielkvist/hugo-terrassa-theme#15]
I'm replacing a Wordpress site using your theme and I really like it. However, I'm not sure how to change the hero image on the home page. I put the image I want in the 'static' folder and changed the config file to the new path, but it did not appear. Any help would be appreciated.

Keep up the good work

**Comment by JohnBlood** [comment]
Also, do you have any plans to add Disqus support?

**Comment by dnlzrgz** [comment]
Hi!

To change the hero image you have to add the image you want to the ```images``` folder, which must be inside the ```static``` folder.

```
 ├── static
        │   ├── favicon.ico
        │   ├── images
        │   │   └── your_hero_image.svg
        │   └── logo.svg
```

And then change the ```images``` property of your ```_index.md``` file inside your content folder:

```
---
title: "Home"
description: ""
images: ["your_hero_image.svg"]
draft: false
menu: main
weight: 1
---

# Terrassa
## The Hugo theme for you. Or for your company.
```

I know it's not a very good explanation, but I hope it helps you.

At this moment I don't plan to add support for Disqus. But it's something I may add in the near future.

**Comment by JohnBlood** [comment]
Thanks for the reply.

Does the image folder need to be named `image` ? I named my image folder `img` .

**Comment by dnlzrgz** [comment]
Unfortunately, yes, it is one of the things I want to change during this week.
But for the moment the folder has to be called ```images```.
I'm sorry for the troubles.

**Comment by JohnBlood** [comment]
No biggie. I've only created a handful of pages, so I'll just need to use the magic of find and replace. :)
