### ISSUE TITLE
multiple 'section' pages

### ISSUE THREAD

**Issue by norcalbiostat** [danielkvist/hugo-terrassa-theme#17]
I'm not a native hugo user, so my terminology is likely incorrect. Hopefully my point gets through. 

The Home page has this 'section' type format, where it's built off of individual `.md` files that live in the `sections` folder. 

Can I have another page that has a similar format? I could kinda see my way into figuring out how to copy/paste/rename the section and sections partials, but i'm not sure how the page is identified as using that structure to begin with. 
[Edit] - ok maybe not now that I found this `archtype` folder that also looks like it has things that define page structure. I really don't want to muck with hugo honestly.

**Comment by dnlzrgz** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Issue #17](https://trello.com/c/i2F3ogds/2-issue-17)

**Comment by dnlzrgz** [comment]
Hi again!

Sections can only be used on the home page. Something that's related to how Hugo treats this page differently ([docs here](https://gohugo.io/templates/homepage/#pages-on-the-homepage)).

I hope I answered your question!

**Comment by norcalbiostat** [comment]
bummer ok. thank you for looking into this
