### ISSUE TITLE
parse failed

### ISSUE THREAD

**Issue by Latifshaikh** [danielkvist/hugo-terrassa-theme#18]
latif@latif:~/latifshaikh$ hugo server -D
Error: "/home/latif/latifshaikh/themes/terrassa/layouts/partials/head.html:10:1": parse failed: template: partials/head.html:10: function "hugo" not defined

**Comment by dnlzrgz** [comment]
I'm sorry, but I'm not able to get that error.
Could you give me more information about the version of hugo you have installed or about the version of Terrassa you are working with?
