### ISSUE TITLE
Alignment of sections

### ISSUE THREAD

**Issue by Shelmith-Kariuki** [danielkvist/hugo-terrassa-theme#19]
![Screen Shot 2019-07-30 at 21 13 03](https://user-images.githubusercontent.com/37449624/62154164-de2e4880-b30e-11e9-9cbc-457f9c799cd1.png)
Hi. I am building my website using this theme. I want the sections at the top to appear as:

Home    About .   Blog  Contact 

instead of

Home    Blog . About .   Contact

Which file should I alter?

**Comment by dnlzrgz** [comment]
Hi!

You should be able to order those items using the ```weight``` property in the front matter of your respective files.

You can see an example [here](https://raw.githubusercontent.com/danielkvist/hugo-terrassa-theme/master/exampleSite/content/_index.md) and [here](https://raw.githubusercontent.com/danielkvist/hugo-terrassa-theme/master/exampleSite/content/about.md).

**Comment by Shelmith-Kariuki** [comment]
Thanks Daniel,

Yeah, the weight works. Another question...is there a way I can change the
theme colour from yellow to something else like blue?

Best,

Shelmith

**Comment by dnlzrgz** [comment]
If you have knowledge of CSS you can create a file called ```custom.css``` inside the folder "css" in "assets" and modify the element directly with your own styles. And at the moment that's the only option for cases like this..

I know it's not an easy option and I'm sorry for the inconvenience.

**Comment by Shelmith-Kariuki** [comment]
Thanks Daniel

I will work with the yellow then. Still looks good.
