### ISSUE TITLE
Error: Error building site: failed to render pages: render of "home" failed:

### ISSUE THREAD

**Issue by ghost** [danielkvist/hugo-terrassa-theme#2]
Hey there, cloned the repo at 2019-01-13 02:41 UTC and loaded it into an other empty site (other than having an index page)

Got the below on generation. 

$ hugo

Total in 11 ms
Error: Error building site: failed to render pages: render of "home" failed: execute of template failed: template: index.html:2:3: executing "main" at <partial "hero.html" ...>: error calling partial: "/home/user/src/site/themes/terrassa/layouts/partials/hero.html:1:11": execute of template failed: template: partials/hero.html:1:11: executing "partials/hero.html" at <index $.Params.image...>: 
error calling index: index of untyped nil

$ hugo version
Hugo Static Site Generator v0.53/extended linux/amd64 BuildDate: 2018-12-24T12:58:46Z

Thanks for the great work!

**Comment by dnlzrgz** [comment]
Hi @apotrebka!

To solve the problem you need to add an "images: []" entry to the front matter of your *_index.md* (according to the format of front matter you have chosen). You can leave it as an empty array and it shouldn't give you any more trouble.

Sorry for the inconvenience!

Edit: Fixed, if you don't want to add the images entry to your front matter you shouldn't have any problems any more.

**Comment by ghost** [comment]
Confirmed working. That line was actually there in the front matter of _index.md, but I had left draft:false

I could chalk this up to my inexperience with Hugo, I believe.

Thanks again!
