### ISSUE TITLE
[FR] Ability to write lists on home page

### ISSUE THREAD

**Issue by erazemk** [danielkvist/hugo-terrassa-theme#20]
I'm writing a website for an open source project and want to add a Features list.
Your template is perfect for the project, but I can't seem to write Markdown lists using asterisks (*).

e.g.

### Features

* This doesn't work

but

\- This does

For now I'm using "\\-" to escape the "-" markdown symbol, but this list writing ability would probably be a lot easier and nicer since it would show a dot instead of the dash.

**Comment by dnlzrgz** [comment]
Hi, thank you very much for the suggestion!

I will take it into account for the next versions of Terrassa.

If you want to create a PR with the necessary changes you're welcome.
