### ISSUE TITLE
Footer requires params.social to be non-empty

### ISSUE THREAD

**Issue by trevortknguyen** [danielkvist/hugo-terrassa-theme#3]
I was trying to build a minimal site with no social media links specified in the config and it appears as though the theme requires at least one social media link.

I'm not sure if the developer intended for this to be the case.

**Comment by dnlzrgz** [comment]
Hi @trevortknguyen!
After the last commit all should work just fine. But if you experience any more issues or there's anything you think is not clear please let me know!
