### ISSUE TITLE
Dropdown menu.

### ISSUE THREAD

**Issue by RazvanCretu** [danielkvist/hugo-terrassa-theme#6]
Hello there,

 I was looking over Hugo's theme and came across this one. I would like to know if it supports dropdown menus, as I would like to categorize my blog posts and a dropdown menu when I `hover` would be great.

**Comment by dnlzrgz** [comment]
Hi @RazvanCretu!
I haven't added support yet for dropdown menus. It's a feature I'd like to implement in the future but I haven't been able to work on it yet.
I'm sorry for the inconvenience.
