### ISSUE TITLE
blog post spacing on large screen

### ISSUE THREAD

**Issue by testingdataviz** [danielkvist/hugo-terrassa-theme#7]
Hi,
I started building a page with the theme and it is really awesome!

I've found there is a problem, though, when having 2 posts on the blog page content list (when it shows 3 at a time). There is a very long separation between the items (one on the very top, and one in the very bottom). This only happens when using a large screen.

Here's an image to show how it looks like: 

![image](https://user-images.githubusercontent.com/35898577/53430577-11328000-39ef-11e9-8dee-0633ee4a1e7b.png)

I dug down and it seems that the problem could be on the grid-auto-flow on style.css ".content". But I couldn't fix it, so I can't suggest a change. Could you have a look? 

Thank you so much for the great work!!!

**Comment by dnlzrgz** [comment]
Hi @testingdataviz!
Thank you very much for open the issue and sorry for the inconvenience.

I can't get into it right now but in a couple of hours I'll try to fix it.
Again, I'm sorry for the inconvenience.

**Comment by testingdataviz** [comment]
Sounds great! No rush on it, and thank you for your attention! 👍

**Comment by dnlzrgz** [comment]
It should be fixed now.
If you have any more problems, don't be afraid to let me know!
