### ISSUE TITLE
Browser support?

### ISSUE THREAD

**Issue by cliffordh** [danielkvist/hugo-terrassa-theme#8]
Do you know the minimum browser level for the CSS and features used? Is IE9, 10 or 11 supported?

**Comment by dnlzrgz** [comment]
Hi @cliffordh! 

Terrassa uses [CSS Grid](https://caniuse.com/#feat=css-grid) and [CSS flexbox](https://caniuse.com/#feat=flexbox). So, as far as I know, neither technology is 100% supported by either IE10 or IE11.

I also don't use any utility like PostCSS to make it optional for the moment. It's something I wanted to work on, but at the moment it's been impossible. I'm really sorry.
